language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: nMrgMC2iwIVeZUYGfUv8Oeiwfw5ZG5Al+u6AIbw2izCpIsr1+oIZEZfR1kheC38RLbyYLGOJzUDwh8GEJy4jB+NHg8lqxmMcXjv7zrcuwEb5OCHw+UUzyZvN1Ja1HVx0Zo3yjFpMRZJam80K9bdi/4OjRdKDP8ut+wHF4roNGL2hU8MBDmwf1N3nqjbbsMGdUYXk9+bg+IZAcA4pL7lYJ2nn/F9FPRVWjdXSIzhvZ2NxbvWfHy9ifdpq3ZFCz77rFCIG8yyKEkzFYu+ef728CusPue7kVios7bQb4xh+QKo0KbE7EZb8ABYq/km4gQ33fxQbalAuJgzzXvDf0aoO6lmGJq7SsCl9JhDQhLs4XcHJu6VUQu2uTzFPRYDEPYdAG5RZn43J3y6iogj04MZ/6d7FwU6fmZmvvko7ZCq1afLlk3tWKC4/2B5E4redqtyWL5LI1wKhCzSZxYlr+PM2fMaPVsS7oS9p0+cYSJ+9ChRkr3KkIR+d4+yAvQqFoKN72iHMf+Imqs8PpXqwU18Wx6gaaNwM4rBM6vycE1NkfaB7Oqm2TH3IZzscvarboWMWCzqFXn4U7IIVQ6Hl0CLgOwqaQao84oEBSDpl4uBejQaqMrM08F3d5GoQz5swBpEPzNgRV9QfWvodqHsGg88HA0akWM+z6oFnFx2yTGQD9cA=
