language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: ijw/aSmwT9oPmCClSJN13JLSIA6g17V1gLUaSVfQSNRpbt61Bs6AZrW8M775UCSlgE+zQfZfVr1fGSMvW+AzQkgrcisdTb1V6OJrQSAxG+f357tv8Iy5iLGGtaHjTySCR86hKhI1L5CQmGRvfuwu7HkAUU9CX101uIFp64rS4cI6wWdUXQQiM12wNffxziNkkZg4dRy5TXm9y6b9Vv/OJcOGegnEUzlv9S4j3o434Z0QCo1i0Hrg6j0kErS4OK26kTDm3Lf7xGsAnF6YG1n+mnuWgQW18vqQAFNk7GmOqjOxlPRTg0+m0okZvxcEEq0PfPywLNC+gAj9iE2pwxjKONvzr4iLmtNWOsnMHs29EZ5NMsG0w6cF6CbtYzUBCVK7tga2N+Ep0DOA/p6n2FQ4H7DhRFj78U2KO0VxKAWEACaFz3CuKwbIh3oyJDQO+6L6FpyXNjVds6IeMv5N280bfd16GdM3yBTI70mebacNwPKDafDwqc9Z2IGRwzPNMsXrB7BXJbcNE38MiXZsmnzgoUHkIvU2nbhs+Iy+AQQS2IQAugD7EYL+2WlqK6/kmu4nsCE66v/rdb1QTq9R7p3SGZS0yFxF+PV7bmfd/gRiSonCXvOyMQ/iZHLQObXXDmic/R16q1R9pnu/Q22zPdMkdxWEtbLX4NDU24M62naRO1M=
