language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: L9TvTk+Eno+IRCF5hWC0tuQ1lKOx3V1G474EFyXvVBIDBNhXd7GuJxKksSaUk4Piwnh6lUsTGepjvsgHVX7G/xXpkg28CBdI/oHyeVX1WWc6Z024U+Zdh2dRrvZ16aRZMAUaU8D3gWpev49t9HSuo51dhe+v1mGAEjO31RZKzLDYE+E2LRDdaUfHFehzIdmqz7tJPTyJDEOaG+fczloFRRH7rwDPTywZdv/GGQBpQVZtzUflH49vcla2b3iVFjYGlxhR03K7LwykJgZcRzZA/Tut5lsMlY73zfeClsaQsl0s5ZjiH1PURkRMJiyGsbzaRC4ZJuXf+R83eF9/A68aRAhhXmoWcktTHDX7KHsv5GNGUVKkdmIh3ix2wQp4tuTDydVAQZCZairHxG7xLgPky8wHFhMfuZ0sjyENBimaIUgazv/PcHDeMqoUkx5Qva/vKdwLy2P/sshBDabySBTib83KDCvqUvTJE7d7uvJKn+h51YoULyPh3a8GEryFMoHIuJfKzvzVLh8LtJW3b9/T1FUUdvaWU7uqveA4fP9Ouu4RUBDvFcfmmOKFgcSjjtQFlXzbLg9JHnGshiidABnfAjliF4NXKJk1VTRP8qPaiXpYLkZ3hhUPmqcg3Am1jvNh3p2a8Ze1SZZfWIlTCDvz7+2gJZrqvWQCkUEUSykUQn8=
