language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: dVwwH+2qJIgWrvJk/jNrTxjN++KENP+VJfe466r8Fr328dib/t0bmLo/dC55MF2ig5o5di+MdHua8kNQgi5I7sFq2lYIAgKxgbAavFMSlhWIk7vtAFei2JIDw59id9wOdCjlwhuTKJyB4nfaYB4dCHnhs0A+4FNyKSWpCR0AEpLoHNsu7HSqSODIMP70tGN2JDSMbpdntBzeDHraY35QTvdmQMx1v2KYxKORqyPhal3gbRXJ0yN+/jpir0uin50OIL6TJ1u61el/bX7LKsH4JOAAvyKMhrQAJdyopaA6eNtHwsREf3JbgZ+dmbSmtpksb1rAOKGvflEedri5MCk5BSB4mvLad+hYVWuT5czAeihMqKC31iokXUkfXf175n3fqwJ1AB2Qhm6GDtCnpmYLgkxnFGe8j0LcwTW4Vl+PB5Cg7HVMSBPflQ3Im2wzTCLnd6gZs1+Wy7rqIUAgGOBKt5jSDvliqqWuSzhRAacfV/LaPlpPYa9PHDX3BNcrFdDt5oyfIWzkMXo+9tPf5KM+RWnwBFxmhg4Yw1E6ttPKcwg6ktCbbh991xxnI+CNQPUBewQ2sEQtQ7Q3nIcHHc6AZQP5l9lRBzxpr29xGOeRYt4OlLGEWicVsOBhfYyBfiGXP2ta5LFpVP1bjCb/Fr4o0UxFsAbxEFkFpnIAHjQ0fmo=
