language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: hIdyt+yawtw8b4xvSM3dBtRvDgRffAQTtcLfAovDjhl3Vba3zFUSAtx0is8u8gKlLM5s7u0wewK0e7Jnwsh8d3j9INiFAoDdYHHOM99FR3ph8jkBt/MmXoBIZzLmViFIwbozQyvD/jdoS/dg62CeCpv/VmcyHWfe1pln3qoMAhnmnOxKZf9/lneSJlxKCgigIXhXqvOCASNqtBVRAaGfDe2kA5a0bJ93Gz5x+a+Wh2CkEHoxMU+XORBz8NGs07QdfIsijUQ1k4W7kqMJAAM5cpD11qj0TJXyi9wt8A6e/4UWB9QCtAjHJPM+8OOcK4SCX5ldnkBqMkl1ttp63IOtVhjftTGaKLvOwKT/4pSxnhII+iLqkRPsZh4bdFhq4oglEdwhM3le1vkVVYTD/V5AXYHT3YHX/GsrH/OJNUltmDcmvJQ/vAcmVqGEKNhyD9ctBRSS1YXhalrVhmIEMcad77EtbBKxkzibFTrld0hl1xe/a47r6EL907Jj4v6fg2NaZevDH6h5ek/mzetYnA0XlHYF8l94djpB5cyd9KjMw5SaZjm1zHIIrB8lBC/ikMjd0FBwGuDuw18UuS4a9vcURj+EuK4qd344VDYncx4GYRGsAKRBJxfxAyu5OHpjHQMnfDoRPzUo0ar9+1AEThfGJfzTqMevI9bBPZldQZKSM9c=
